**SCALAR OPERATIONS ON AN ARRAY**

In [6]:
import numpy as np
array1 = np.array([[1,2,3,4], [5,6,7,8]])
array1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
array1*array1

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [10]:
array1 ** array1

array([[       1,        4,       27,      256],
       [    3125,    46656,   823543, 16777216]], dtype=int32)

In [11]:
array1 ** 3

array([[  1,   8,  27,  64],
       [125, 216, 343, 512]], dtype=int32)

In [12]:
array1**3 -array1

array([[  0,   6,  24,  60],
       [120, 210, 336, 504]])

These are all scalar operations on arrays

**INDEXING WITH ARRAYS**

In [94]:
arr = np.arange(10, 60, 3)
arr

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58])

In [95]:
arr[7:] = 44
arr

array([10, 13, 16, 19, 22, 25, 28, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44])

Now when dealing with arrays in numpy, memory is managed and no new memory is allocated for a variable that is assigned to
an array slice

In [96]:
arr2 = arr[:6]
arr2

array([10, 13, 16, 19, 22, 25])

In [97]:
#a change in arr2 will result in a corresponding change in arr
arr2[:] = 334
print(arr2, "\n",  arr)

[334 334 334 334 334 334] 
 [334 334 334 334 334 334  28  44  44  44  44  44  44  44  44  44  44]


to ensure a new memory is allocated for the new variable you want, use the copy function

In [39]:
arr3 = arr.copy()
arr3

array([334, 334, 334, 334, 334, 334,  28,  44,  44,  44,  44,  44,  44,
        44,  44,  44,  44])

In [40]:
arr3[:] = 9990
print(arr3, '\n', arr)

[9990 9990 9990 9990 9990 9990 9990 9990 9990 9990 9990 9990 9990 9990
 9990 9990 9990] 
 [334 334 334 334 334 334  28  44  44  44  44  44  44  44  44  44  44]


In [98]:
#For multidimensional arrays:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
arr2d[1][2]

6

In [100]:
arr2d[0][1]

2

In [101]:
arr2d[0:, :1]

array([[1],
       [4],
       [7]])

In [102]:
for i in range(arr2d.shape[0]):
    arr2d[i] = i
arr2d

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [103]:
l = np.array([1,2,3,4])
list(enumerate(l))

[(0, 1), (1, 2), (2, 3), (3, 4)]

In [104]:
l[:3] = 45
l

array([45, 45, 45,  4])

In [105]:
#Another way of accesing the rows:
arr2d

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [106]:
arr2d[0]

array([0, 0, 0])

In [107]:
arr2d[[0,1,2]]

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])

In [108]:
arr2d[[2,0,1]]

array([[2, 2, 2],
       [0, 0, 0],
       [1, 1, 1]])

In [109]:
print(arr2d[0][1], arr2d[0:, :1], arr2d[[0,1]])

0 [[0]
 [1]
 [2]] [[0 0 0]
 [1 1 1]]


**arr2d[0][1]** is to access a single element in the second column(1) of the first row(0)

**arr2d[0:, :1]** is to yield an array of all the elements in the first column for all the rows

**arr2d[[0,1]]** is to yield an array of all the elements in the first and second rows (according to the index placement)