**UNIVERSAL ARRAY FUNCTIONS**
1. arange
2. sqrt
3. exp
4. random
5. addition
6. maximum

In [1]:
import numpy as np

In [2]:
#For arange
np.arange(2, 15, 3)

array([ 2,  5,  8, 11, 14])

In [3]:
#for sqrt,  you can find the square root of all the elements in array
qq = np.arange(1, 27, 3)
pp = np.sqrt(qq)
print(qq, '\n', pp)

[ 1  4  7 10 13 16 19 22 25] 
 [1.         2.         2.64575131 3.16227766 3.60555128 4.
 4.35889894 4.69041576 5.        ]


In [4]:
#for the exp function, it finds the exponent of each array element.
a = np.exp(qq)
a

array([2.71828183e+00, 5.45981500e+01, 1.09663316e+03, 2.20264658e+04,
       4.42413392e+05, 8.88611052e+06, 1.78482301e+08, 3.58491285e+09,
       7.20048993e+10])

In [5]:
#for the add function, it has two arguments. It adds the two arrays together into one array
b = np.add(qq, pp)
b

array([ 2.        ,  6.        ,  9.64575131, 13.16227766, 16.60555128,
       20.        , 23.35889894, 26.69041576, 30.        ])

In [6]:
#for the maximum function, it has two arguments. it compares the array elements in each variable. The bigger one is 
#added to a new array and the process continues for corresponding elements.
d = np.maximum(qq,pp)
d

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25.])

**LOADING AND SAVING ARRAYS IN PROJECT FILES**

In [7]:
arr = np.arange(14)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [8]:
#to save single arrays:
np.save('Saved', arr)

In [9]:
load = np.load('Saved.npy')
load

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [10]:
#to save multiple arrays, you zip the file using savez instead of save and the file extension is npz instead of npy
brr = np.arange(20)
np.savez('saved.npz',  x = arr, y =  brr)

In [11]:
#Let's load the file, 
load_file = np.load('saved.npz')

#to print out the file, you have to specify the array because it is saving multiple arrays
load_file['x']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

Do note that these arrays cannot be loaded with any text editor or software apart from python software. To be able to load the file with notepad or a text editor, you will have to save it in a txt file.

In [12]:
np.savetxt('note.txt', arr, delimiter = ',')
load_file_txt = np.loadtxt('note.txt', delimiter = ',')
load_file_txt

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13.])

Note that the output is in float format. This is the default settings of saving in txt format.

In [13]:
#another example
array_1 = np.arange(20)
array_2 = np.arange(10, 40, 4)
array_3 = np.arange(7)

#saving and loading one array file
first_file = np.save('first', array_1)
load_first = np.load('first.npy')
load_first

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
#saving and loading multiple array files, we use the zip format
second_file = np.savez('second.npz', a = array_1, b = array_2, c = array_3)
load_second_file = np.load('second.npz')
load_second_file['b']

array([10, 14, 18, 22, 26, 30, 34, 38])

In [15]:
#saving in txt format
third_file = np.savetxt('third.txt', array_3, delimiter = ',')
load_third = np.loadtxt('third.txt', delimiter = ',')
load_third

array([0., 1., 2., 3., 4., 5., 6.])