In [1]:
import numpy as np
my_list = [1, 2, 3, 4, 5, 6]
my_array = np.array(my_list)
my_array

array([1, 2, 3, 4, 5, 6])

The array created above is a linear array of one dimension. 
Now to create an array of two dimensions:


In [19]:
my_list2 = [7, 8, 9, 10, 11, 12]
new_arr = np.array([my_list, my_list2])
new_arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [15]:
#Finding out the row and column values of an array
new_arr.shape

(2, 6)

In [17]:
#Finding out the datatype of the members of the array
new_arr.dtype

dtype('int32')

Special functions in numpy include:
1. zeros
2. ones
3. empty
4. eye
5. arrange

In [20]:
#the zeros function creates a numpy array of 1 * n array or matrix in which all elements are 0
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
#specify the number of rows with [m, n] in the argument
np.zeros([3, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
#the ones function creates a numpy array of 1 * n array or matrix in which all elements are 1
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
#specify the number of rows with [m, n] in the argument
np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
#the empty function performs the same as the zeros. It gives approximate values for zero.
np.empty(4)

array([1.37013367e-311, 1.37015169e-311, 0.00000000e+000, 7.52030278e+252])

In [29]:
np.empty([2,4])

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.18570189e-321, 1.40495219e-309,
        4.55718211e-303]])

In [32]:
#the eye function produces an identity matrix(a matrix in which the diagonals are 1). 
#Do not that it takes only a single argument and not a list.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
#the np.arange(start, stop, step) function yields an array that consists of an arithmetic progression of numbers
#that includes the start number and differs by the step number for each element. It however does not include the stop
np.arange(5, 10, 2)

array([5, 7, 9])

In [35]:
np.arange(6, 23)

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22])

In [36]:
range(6, 23)

range(6, 23)

In [37]:
list(range(6, 23))

[6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22]

In [38]:
list(range(6, 23, 4))

[6, 10, 14, 18, 22]

In [41]:
list(enumerate(range(6, 56, 5)))

[(0, 6),
 (1, 11),
 (2, 16),
 (3, 21),
 (4, 26),
 (5, 31),
 (6, 36),
 (7, 41),
 (8, 46),
 (9, 51)]

The arange function is similar to the range function. The range function however is a lazy function and needs to be listed.
The enumerate function yields the index and value in a tuple for a list or a tuple.

In [42]:
np.arange(23, 2, -4)

array([23, 19, 15, 11,  7,  3])