**DATAFRAME**

In [19]:
#a two or more dimensional matrix with index and column names.
import pandas as pd
from pandas import Series, DataFrame
xcc = np.array([1,2,3,4])
lxc = Series(xcc)
df = lxc.to_frame()
df

0
0  1
1  2
2  3
3  4

In [26]:
#to access the columns
df.columns

RangeIndex(start=0, stop=1, step=1)

In [35]:
DataFrame(df)

0
0  1
1  2
2  3
3  4

In [92]:
#to create a column with Nan values
rev = DataFrame(df, columns = [0, 'Niece', '90'])
rev

0  Niece  90
0  1    NaN NaN
1  2    NaN NaN
2  3    NaN NaN
3  4    NaN NaN

In [93]:
#to access the rows
rev.iloc[0] #for postional based indexing

0        1.0
Niece    NaN
90       NaN
Name: 0, dtype: float64

In [94]:
#for label based indexing
rev.loc[1]

0        2.0
Niece    NaN
90       NaN
Name: 1, dtype: float64

In [95]:
#accessing columns
rev.iloc[:, 1] #This accesses all the rows and the second columns  for postional indexing

0   NaN
1   NaN
2   NaN
3   NaN
Name: Niece, dtype: float64

In [96]:
#for labelled based index
rev.loc[:, 'Niece']

0   NaN
1   NaN
2   NaN
3   NaN
Name: Niece, dtype: float64

In [97]:
#for reversing the row index
rev.iloc[:: -1]

0  Niece  90
3  4    NaN NaN
2  3    NaN NaN
1  2    NaN NaN
0  1    NaN NaN

In [98]:
#for reversing the column index
rev.iloc[:, ::-1]

90  Niece  0
0 NaN    NaN  1
1 NaN    NaN  2
2 NaN    NaN  3
3 NaN    NaN  4

In [99]:
value = np.array([10,11,2,22])
rev['Niece']
rev

0  Niece  90
0  1    NaN NaN
1  2    NaN NaN
2  3    NaN NaN
3  4    NaN NaN

In [100]:
#Note for numpy the length of the array must  be the same as the length of the dataframe. This means the dataframe index 
#should be able to complete the arrays. However for pandas series, it is not the case.
new_series = Series([300, 'Nige'], index = [0, 2])
rev['90'] = new_series
rev

0  Niece    90
0  1    NaN   300
1  2    NaN   NaN
2  3    NaN  Nige
3  4    NaN   NaN

In [102]:
#Notice how the series only fills the specified indexes 
#you can also delete columns but note, you cant get it back
del rev['90']
rev

0  Niece
0  1    NaN
1  2    NaN
2  3    NaN
3  4    NaN

In [103]:
#dictionary to dataframe
sample = {'company':['A','B'], 'Profit':[1000, 500]}
df_2 = DataFrame(sample)
df_2

company  Profit
0       A    1000
1       B     500

In [111]:
#Negative indexing ivolves the elimnating of the index
rev[-2:]

0  Niece
2  3    NaN
3  4    NaN

In [112]:
rev.index.values

array([0, 1, 2, 3], dtype=int64)

In [113]:
rev.index.values[-2:] #notice how the first and second indexes have been elimated

array([2, 3], dtype=int64)

In [129]:
rev[-1:] #the larger the negative number i.e(-1, -2, -3), the smaller the resulting dataframe

0  Niece
3  4    NaN

In [130]:
rev[-2:]

0  Niece
2  3    NaN
3  4    NaN

In [131]:
rev.index[-2:] #same thing here

RangeIndex(start=2, stop=4, step=1)

In [132]:
rev[:-2] #eliminates the final two indexes

0  Niece
0  1    NaN
1  2    NaN

In [137]:
rev[:-1]

0  Niece
0  1    NaN
1  2    NaN
2  3    NaN

In [138]:
rev.index.values[:-2]

array([0, 1], dtype=int64)

In [139]:
#for range of index
rev.index[2:3]

RangeIndex(start=2, stop=3, step=1)

In [ ]:
#Note that index does not support mutable operations. You cannot change the index value at any point in time.